### ISSUE TITLE
SUBSCRIBE button not Responsive

### ISSUE THREAD

**Issue by harsh56-png** [harsh56-png/vikspik.netlify.app-photography-website#1]
The SUBSCRIBE button in the contact.html file isn't responsive and does not properly align and resize with respect to devices.
Please help me out with it.

Thank You

**Comment by amar-prabhu-29** [comment]
Are you looking for the subscribe button to be centered in all devices?

If so, assign me the issue, ill work on it.
If not please explain the expected behavior of the subscribe button in smaller devices.

**Comment by harsh56-png** [comment]
> Are you looking for the subscribe button to be centered in all devices?
> 
> If so, assign me the issue, ill work on it.
> If not please explain the expected behavior of the subscribe button in smaller devices.

Hey there, yes please, I need the button to be centered for all devices and also get smaller and bigger with respect to small and large screens.

**Comment by amar-prabhu-29** [comment]
Have issued a pull request for the same. 
Review changes and merge please.
